---
title: "MS_for_proteomics_tutorial"
author: "Sam Siljee"
date: "24/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r packages, include=FALSE}
#Install Spectra using BiocManager
library("Spectra")
library("rpx")
library("mzR")
library("tidyverse")
```

## Starting with Spectra
```{r starting with spectra, include=FALSE}
# first part of MS data
spd <- DataFrame(msLevel = c(1L, 2L),
          rtime = c(10.1, 24))
spd

#still requires raw data to be more like MS data. Use list

spd$mz <- list(c(100, 103.2, 104.3, 106.5),
     c(45.6, 120.4, 190.2))

spd$intensity <- list(c(200, 400, 34.2, 17),
     c(12.3, 15.2, 6.8))

spd

#simple dataframe set up, nothing specific to MS yet. Now we can use the `Spectra` package to convert generic dataframe to object specific to MS

sp <- Spectra(spd)

#sp is an object of class "Spectra" which is specific to MS datasets
sp

#As can be seen, most of the variables are not populated
spectraVariables(sp)

#The values of these variables can be accessed
spectraData(sp)

# as well as individual spectra
peaksData(sp)

peaksData(sp)[[1]]
```

## Getting raw MS data from a public repository
```{r getting raw MS data from a public repository, include=FALSE}
#The following code from the tutorial does not run, likely due to server issues with the repository. I have commented it out for now, downloaded the datasets separately, and loaded them from there. Note that the dataset is too large to load to github, so I have added it to the gitignore


#px1 <- PXDataset("PXD000001")

#`px1` is not a dataset in and of itself, however it is a method to query the EBI database
#px1

#review files in px1, we are interested in #7
#pxfiles(px1)

#create a variable for file #7
#f <- "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML"

#download results
#mzf <- pxget(px1, f)

#mzf is path to raw dataset
#mzf

#setting up the actual dataset, using the download approach as described above. Note that this will overwrite the `sp` variable previously defined
sp <- Spectra("~/Coding/MS_for_proteomics_tutorial/data/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzML")

#The values of these variables can be accessed, as with the small practice dataset, note that more variables are actually included
spectraVariables(sp)

# as well as individual spectra
peaksData(sp)

peaksData(sp)[[1]]

#check that there are indeed 7434 spectra in this dataset
length(sp)

#look at the first few spectra
spectraData(sp)

#you can use a function to access specific aspects
msLevel(sp)

#table the number of MS1 and MS2 scans
table(msLevel(sp))

#Can also look at retention times
rtime(sp)

#and we can look at the range of retention time, note that the first data point does not have any useful data
range(rtime(sp))

#can also filter by certain variables
sp2 <- filterMsLevel(sp, 2)

sp2

#now to visualise the chromatogram. the `tic` function gives total ion current. the chromatogram only makes sense for MS1 data, so first extract the MS1 only
sp1 <- filterMsLevel(sp, 1)

#get retention times
rtime(sp1)

#get total ion currents
tic(sp1)

#then get the retention times, and ion times and plot them
plot(rtime(sp1), tic(sp1), type = "l")

#can also subset to select a specific spectrum, works like a list
#for example extracting spectrum number 1000, will give a Spectra object of length 1, with the thousandth spectrum
sp[1000]

#Or select scans from 1000 to 2000
sp[1000:2000]

#there is also a function to plot a spectrum, this give the classic m/z vs intensity plot
plotSpectra(sp[1000])

#could also create this plot manually, now that we know how to access this data, as follows
#create a Spectra object of scan number 1000
sp1000 <- sp[1000]

#extract the mz values, this creates a list of length 1, so select the first list
mz(sp1000)[[1]] 

#extract the intensities, as above
intensity(sp1000)[[1]]

#and plot them
plot(mz(sp1000)[[1]],
     intensity(sp1000)[[1]],
     type = "h")
```

## Visualisation
```{r visualisation, include=FALSE}
#making a chromatogram, code previously used, however this time adding a red line for the selected ion (for MS2)
plot(rtime(sp1), tic(sp1), type = "l")
abline(v = rtime(sp)[2807], col = "red")

#Now using tidyverse to make a chromatogram, another way to get the same plot. First to filter for MS1, then extract Dataframe (capital D denotes Bioconductor), then as tibble to use in ggplot for more flexibility
sp %>%
  filterMsLevel(1) %>%
  spectraData() %>%
  as_tibble() %>%
  ggplot(aes(x = rtime, y = totIonCurrent)) +
    geom_line() +
    geom_vline(xintercept = rtime(sp[2807]), colour = "red")

#now to extract the set of scans related to scan #2807. Just to review it first briefly. Note that it's MS1 level
sp[2807]

#note that following scan 2807, there a set of MS2 scans which originate from scan 2807
sp[2807:2817]

#however there is a specific function to filter for scans related to a particular MS1 scan
filterPrecursorScan(sp, 2807)

#creating a subset
spx <- filterPrecursorScan(sp, 2807)

#starting easy, plotting the MS1 scan
plotSpectra(spx[1])

#now to highlight the selected peaks. First extract the MZ values of the precursors. there are 11 scans in spx, so there will be 11 results. one is NA because it is the MS1 scan
precursorMz(spx)

#adding the two together, removing the first NA of the precursor MZ values, limiting the X values, highlighting the first MS2 scan in red
plotSpectra(spx[1], xlim = c(400, 1000))
abline(v = precursorMz(spx)[-1], col = "gray")
abline(v = precursorMz(spx)[2], col = "red")

#zooming in further, by limiting the x axis further. Line graph is more appropriate at this level
plotSpectra(spx[1], xlim = c(521, 522), type = "l")
abline(v = precursorMz(spx)[-1], col = "gray")
abline(v = precursorMz(spx)[2], col = "red")

#now to plot the MS2 scans
#first filter for MS2
plotSpectra(filterMsLevel(spx, 2))
```

##Sequence identification
```{r sequence identification, include = FALSE}

```

## Extra code
```{r extra code that I experimented with, echo=FALSE}
#I wanted to use the data to check whether it is indeed the top 10 precursors that get taken for MS2 scans.

#Checking again the numbers of the different MS levels
table(msLevel(sp))

#Dividing the number of MS2 scans by the number of MS1 scans to get the ratio
sum(msLevel(sp)==2)/sum(msLevel(sp)==1)

#This gives a ratio well below the expected 10. Then I remebered that the scans at the start of the run are not useful, and will therefore not have any MS2 scans. Therefore I will likely get a more realistic result if I filter for scans done during the bulk of the run. Looking at the chromatogram again, so we can choose what range to select
plot(rtime(sp1), tic(sp1), type = "l")

#retention time between 1300 and 2800 looks good, so I'll filter for that. First create a new fitlered Spectra object
spfilt <- filterRt(sp, c(1300, 2800))

#then get a ratio again. Looks much better!
sum(msLevel(spfilt)==2)/sum(msLevel(spfilt)==1)

#Reproducing the graph of MS1 spectrum with highlighted ions selected for MS2, but in ggplot rather than the plot spectrum function
data.frame(mz = mz(spx[1])[[1]], intensity = intensity(spx[1])[[1]]) %>%
  ggplot() +
  geom_linerange(aes(x = mz, ymax = intensity, ymin = 0)) +
  geom_vline(xintercept = precursorMz(spx[-1]), colour = "gray") +
  geom_vline(xintercept = precursorMz(spx[2]), colour = "red") +
  xlim(400, 1000)

#Zoomed in version
data.frame(mz = mz(spx[1])[[1]], intensity = intensity(spx[1])[[1]]) %>%
  ggplot() +
  geom_line(aes(x = mz, y = intensity)) +
  geom_vline(xintercept = precursorMz(spx[-1]), colour = "gray") +
  geom_vline(xintercept = precursorMz(spx[2]), colour = "red") +
  xlim(521, 522)
```

